### PR TITLE
Add telegram as an alert destination / added multi alert support

### PR DESCRIPTION
**Pull request by ijaron**
Added telegram as an alert destination via telegram bot.
To use, get api_token from botfather on telegram.
chat_id can be found by adding rawdatabot to the chat you wish to have alerts go to if a group chat, or start a chat with rawdatabot to get your user_id which will be your chat_id for single user chat.
Can also get chat_id by reguesting https://api.telegram.org/bot<API_TOKEN>/getUpdates after starting a chat with your bot

### CODE REVIEW

**Comment by Gilles94500** [comment]
I have downloaded the android telegram appli. I have created a telegram account . I have created a bot with botfather, so I have now the api_token and I have also got the chat_id.

I have amended the python code (controller.py and config.json) 

To make it work, I have had to add : import urllib

 

Now, I get the message : “May 15 11:49:14 raspberrypi garage_controller: Sending Telegram message”

But I don’t receive any telegram msg.

Did I miss something ? (I have never used telegram messenger before)

 

Thanks

Gilles

**Comment by ijaron** [comment]
It is likely that you have to start a chat with your bot before it will send messages. I haven't tested it without starting a chat first. 
To start a chat just send your bot "/start"

**Comment by Gilles94500** [comment]
You were right. It works now when I have first started the chat with  “/start”.

Thanks a lot.

 

Regards,

Gilles

**Comment by andrewshilliday** [comment]
Thanks for the contribution.  I will merge this in now.

**Pull request merged**
