### PR TITLE
Enhanced email alerts

### LINKED ISSUE #82: Request desired state
Hi @andrewshilliday - thanks for sharing this project :+1:  I have it up and running as designed!

I'd like to adapt it to take into account the current state e.g. if I tell it to open the garage door and it's already open (or opening) then don't do anything.

It's so I can introduce it into my home automation and use a webhook like:
```http://192.168.0.100:8081/clk?id=left&desired_state=open``` or similar

Any pointers you can provide or ideas how this may be done? I'm happy to take a crack at the code but I'm not that familiar with it (or Python in general).

For example if I arrive home in my car, I would like it to be triggered to open if it isn't open already.

Cheers, Adrian.

### PR DESCRIPTION
**Pull request by adriangibbons**
**Enhanced email alerts**
Emails being sent were being marked as Spam by SpamAssassin on my mail server. This was due to missing fields such as the Date and Message-ID. I've added this. And re-formatted the JSON config and added an email subject parameter.

```desired_state``` functionality for another time 👍 

Thanks again for this awesome project. Cheers, Adrian.

### CODE REVIEW

**Comment by adriangibbons** [comment]
Just added a couple more commits to enhance email alerts.

**Comment by andrewshilliday** [comment]
Thanks for the suggested changes.  it looks like you're submitted commits for two new features, a fix to the email handling, and a new desired state toggle.   Would you mind submitting them as seperate pull requests?  I could merge in the email change immediately, but the desired state feature will need to take some thought.  The reason that I never implemented something like this to begin with was that the sensors don't provide the controller with perfect information about the state of the doors.  In otherwords, given some arbitrary state of the garage door, the controller has no way of knowing whether "pushing the button" will open or close the doors (e.g., the doors could be half way open, and you might want to close them but pushing the button would actually open them all the way).  HAve you figured out some way to account for that?

**Comment by adriangibbons** [comment]
Hi @andrewshilliday - I actually wanted to send two PRs, but Github only seemed to let me add the additional changes to my existing PR. I'll cancel this one and then re-submit just the commits for the enhanced email.

Re: doors being half way open, the way I decided to handle that is to ignore the toggle when doors are in the state 'opening' or 'closing' ```if state == 'opening' or state == 'closing':``` (commit c36517e)

Though I guess that it could be made to be a little more sophisticated. I.e.:
 - Still fire if ```desired_state``` is "toggle" regardless of whether opening or closing.
 - Still fire if opening and ```desired_state``` is "closed"
 - Still fire if closing and ```desired_state``` is "open"

What do you think of that? Cheers, Adrian.

**Comment by adriangibbons** [comment]
Just revered the commits related to the ```desired_state``` functionality. So just email alerts in this PR now! Cheers, Adrian.

**Pull request merged**
